import React from 'react';
import {
  StyleSheet,
  Dimensions,
} from 'react-native';
import { palette } from './palette';

const chosenFont = "../assets/fonts/AbhayaLibre-Bold.ttf" // or "Avenir"

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

const expectationStyles = StyleSheet.create({
  background: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  container: {
    flex: 1,
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
    overflow: 'visible',
  },
  backButton: {
    position: 'absolute',
    top: SCREEN_HEIGHT * 0.05,
    left: SCREEN_WIDTH * 0.05,
    zIndex: 10,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  title: {
    fontSize: 28,
    fontFamily: chosenFont,
    color: palette.mediumBrown,
    fontWeight: '600',
  },
  description: {
    fontSize: 16,
    fontFamily: chosenFont,
    color: palette.darkBrown,
    lineHeight: 24,
    textAlign: 'center',
    marginBottom: 24,
    paddingHorizontal: 20,
  },
  examplesContainer: {
    width: '100%',
    paddingHorizontal: 30,
    marginTop: 16,
  },
  examplesTitle: {
    fontSize: 16,
    fontFamily: chosenFont,
    color: palette.darkBrown,
    fontWeight: '600',
    marginBottom: 12,
  },
  example: {
    fontSize: 16,
    fontFamily: chosenFont,
    color: palette.darkBrown,
    fontStyle: 'italic',
    lineHeight: 24,
    marginBottom: 8,
    paddingLeft: 16,
  },
  continueButton: {
    position: 'absolute',
    bottom: SCREEN_HEIGHT * 0.05,
    right: SCREEN_WIDTH * 0.1,
    backgroundColor: palette.lightBeige,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  continueButtonText: {
    fontSize: 18,
    fontFamily: chosenFont,
    color: palette.mediumBrown,
  },
    message: {
    fontSize: 20,
    fontFamily: chosenFont,
    color: palette.darkBrown,
    lineHeight: 30,
    textAlign: 'center',
    paddingHorizontal: 30,
  },
  backToPortalButtonMain: {
    position: 'absolute',
    bottom: SCREEN_HEIGHT * 0.05,
    left: SCREEN_WIDTH * 0.5,
    transform: [{ translateX: -SCREEN_WIDTH * 0.2 }],
    backgroundColor: palette.lightBeige,
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
    width: SCREEN_WIDTH * 0.4,
  },
  backToPortalButtonText: {
    fontSize: 18,
    fontFamily: chosenFont,
    color: palette.mediumBrown,
    fontWeight: '600',
  },
  backToPortalButton: {
    position: 'absolute',
    bottom: SCREEN_HEIGHT * 0.05,
    left: SCREEN_WIDTH * 0.1,
    backgroundColor: 'transparent',
    paddingVertical: 10,
    paddingHorizontal: 16,
    zIndex: 10,
  },
  backToPortalText: {
    fontSize: 16,
    fontFamily: chosenFont,
    color: palette.slate,
    textDecorationLine: 'underline',
  },
    sectionTitle: {
    fontSize: 28,
    fontFamily: chosenFont,
    color: palette.mediumBrown,
    fontWeight: '600',
    marginBottom: 24,
    textAlign: 'center',
  },
  bulletList: {
    marginBottom: 24,
    width: '100%',
    paddingHorizontal: 30,
  },
  bulletPoint: {
    fontSize: 18,
    fontFamily: chosenFont,
    color: palette.darkBrown,
    lineHeight: 32,
    marginBottom: 8,
  },
  prompt: {
    fontSize: 18,
    fontFamily: chosenFont,
    color: palette.darkBrown,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingHorizontal: 20,
    lineHeight: 26,
    marginBottom: 16,
  },
  textBox: {
    backgroundColor: palette.lightBeige,
    borderRadius: 16,
    padding: 16,
    fontSize: 17,
    fontFamily: chosenFont,
    color: palette.darkBrown,
    minHeight: 120,
    width: '90%',
    marginTop: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: palette.lightGray,
    textAlignVertical: 'top',
  },
  savebutton: {
    backgroundColor: palette.slate,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    width: '90%',
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  savebuttontext: {
    fontSize: 16,
    fontFamily: chosenFont,
    color: palette.cream,
    fontWeight: '600',
  },
  buttonRow: {
    flexDirection: 'row',
    width: '90%',
    gap: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButton: {
    backgroundColor: 'transparent',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: palette.slate,
    flex: 1,
  },
  cancelButtonText: {
    fontSize: 16,
    fontFamily: chosenFont,
    color: palette.slate,
    fontWeight: '600',
  },
  saveButtonEdit: {
    flex: 1,
  },
  editButton: {
    backgroundColor: palette.slate,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    width: '90%',
    marginTop: 8,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  editButtonText: {
    fontSize: 16,
    fontFamily: chosenFont,
    color: palette.cream,
    fontWeight: '600',
  },
  savedLabel: {
    fontSize: 16,
    fontFamily: chosenFont,
    color: palette.mediumBrown,
    fontWeight: '600',
    marginTop: 24,
    marginBottom: 8,
    textAlign: 'center',
  },
  savedTextBox: {
    backgroundColor: palette.lightBeige,
    borderRadius: 16,
    padding: 16,
    fontSize: 17,
    fontFamily: chosenFont,
    color: palette.darkBrown,
    minHeight: 120,
    width: '90%',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: palette.lightGray,
    textAlignVertical: 'top',
    opacity: 0.8,
  },
  scrollView: {
    flex: 1,
    width: '100%',
  },
  scrollContent: {
    paddingBottom: 120,
  },


});

export default expectationStyles;