import React from 'react';
import {
  StyleSheet,
  Dimensions,
} from 'react-native';
import { palette } from './palette';

const chosenFont = "../assets/fonts/AbhayaLibre-Bold.ttf" // or "Avenir"

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

const portalStyles = StyleSheet.create({
  background: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  container: {
    flex: 1,
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
    overflow: 'visible',
  },
  backButton: {
    position: 'absolute',
    top: SCREEN_HEIGHT * 0.05,
    left: SCREEN_WIDTH * 0.05,
    zIndex: 10,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 17,
    marginTop: 35,
  },
  title: {
    fontSize: 28,
    fontFamily: chosenFont,
    color: palette.mediumBrown,
    fontWeight: '600',
  },
  description: {
    fontSize: 16,
    fontFamily: chosenFont,
    color: palette.darkBrown,
    lineHeight: 24,
    textAlign: 'center',
    marginBottom: 24,
    paddingHorizontal: 20,
  },
  examplesContainer: {
    width: '100%',
    paddingHorizontal: 30,
    marginTop: 16,
  },
  examplesTitle: {
    fontSize: 16,
    fontFamily: chosenFont,
    color: palette.darkBrown,
    fontWeight: '600',
    marginBottom: 12,
  },
  example: {
    fontSize: 16,
    fontFamily: chosenFont,
    color: palette.darkBrown,
    fontStyle: 'italic',
    lineHeight: 24,
    marginBottom: 8,
    paddingLeft: 16,
  },
  continueButton: {
    position: 'absolute',
    bottom: SCREEN_HEIGHT * 0.05,
    right: SCREEN_WIDTH * 0.1,
    backgroundColor: palette.lightBeige,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  continueButtonText: {
    fontSize: 18,
    fontFamily: chosenFont,
    color: palette.mediumBrown,
  },
    frogsContainer: {
    position: 'absolute',
    top: SCREEN_HEIGHT * 0.1,
    right: SCREEN_WIDTH * 0.05,
    alignItems: 'center',
    zIndex: 5,
    gap: .1,
  },
  frogsImage: {
    width: 150,
    height: 65,
    resizeMode: 'contain',
  },
  labelsContainer: {
    flexDirection: 'row',
    width: 150,
    justifyContent: 'space-between',
    marginTop: 8,
    paddingHorizontal: 5,
  },
  userGraphicLabel: {
    fontSize: 14,
    fontFamily: 'Avenir',
    color: palette.darkBrown,
    fontWeight: '500',
    textAlign: 'center',
    flex: 1,
  },
  spiralTouchable: {
    position: 'absolute',
    width: SCREEN_WIDTH * 0.4,
    height: SCREEN_HEIGHT * 0.4,
    bottom: SCREEN_HEIGHT * 0.45,
    left: SCREEN_WIDTH * 0.1,
    zIndex: 11,
    justifyContent: 'center',
    alignItems: 'center',
  },
  one: {
    width: SCREEN_WIDTH * 0.2,
    height: SCREEN_WIDTH * 0.2,
    resizeMode: 'contain',
    marginLeft: SCREEN_WIDTH * 0.05,
  },
  invite: {
    position: 'absolute',
    width: SCREEN_WIDTH * 0.32,
    height: SCREEN_WIDTH * 0.32,
    bottom: SCREEN_HEIGHT * 0.45 + (SCREEN_HEIGHT * 0.35) / 2 + (SCREEN_WIDTH * 0.2) / 2 - 10,
    left: SCREEN_WIDTH * 0.1 + (SCREEN_WIDTH * 0.4) / 2 + SCREEN_WIDTH * 0.002 - (SCREEN_WIDTH * 0.32) / 2 - SCREEN_WIDTH * 0.02,
    zIndex: 12,
    resizeMode: 'contain',
  },
  spiral: {
    position: 'absolute',
    width: SCREEN_WIDTH * 0.4,
    height: SCREEN_HEIGHT * 0.4,
    bottom: SCREEN_HEIGHT * 0.45,
    left: SCREEN_WIDTH * 0.1,
    zIndex: 10,
    resizeMode: 'contain',
  },
  expectationsTouchable: {
    position: 'absolute',
    width: SCREEN_WIDTH * 0.4,
    height: SCREEN_HEIGHT * 0.4,
    bottom: SCREEN_HEIGHT * 0.32,
    left: SCREEN_WIDTH * 0.6,
    zIndex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  two: {
    width: SCREEN_WIDTH * 0.2,
    height: SCREEN_WIDTH * 0.2,
    resizeMode: 'contain',
  },
  expectationsImage: {
    position: 'absolute',
    width: SCREEN_WIDTH * 0.32,
    height: SCREEN_WIDTH * 0.32,
    bottom: SCREEN_HEIGHT * 0.32 + (SCREEN_HEIGHT * 0.35) / 2 + (SCREEN_WIDTH * 0.2) / 2 - 10,
    left: (SCREEN_WIDTH * 0.6 + (SCREEN_WIDTH * 0.4) / 2) - (SCREEN_WIDTH * 0.32) / 2 - SCREEN_WIDTH * 0.02,
    zIndex: 12,
    resizeMode: 'contain',
  },
  reflectContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0,
    position: 'absolute',
    width: SCREEN_WIDTH * 0.4,
    height: SCREEN_HEIGHT * 0.4,
    bottom: SCREEN_HEIGHT * 0.15,
    left: SCREEN_WIDTH * 0.1,
    zIndex: 1,
  },
  reflectTouchable: {
  },
  lock: {
    width: SCREEN_WIDTH * 0.2,
    height: SCREEN_WIDTH * 0.2,
    resizeMode: 'contain',
  },
  assurances: {
    position: 'absolute',
    width: SCREEN_WIDTH * 0.32,
    height: SCREEN_WIDTH * 0.32,
    bottom: SCREEN_HEIGHT * 0.15 + (SCREEN_HEIGHT * 0.35) / 2 + (SCREEN_WIDTH * 0.2) / 2 - 10,
    left: (SCREEN_WIDTH * 0.1 + (SCREEN_WIDTH * 0.4) / 2) - (SCREEN_WIDTH * 0.32) / 2 - SCREEN_WIDTH * 0.02,
    zIndex: 12,
    resizeMode: 'contain',
  },

  elementcontainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    gap: 30,
    paddingTop: 5,
  },
  strokemap: {
    // width: SCREEN_WIDTH * 0.4,
    // position: 'absolute',
    // width: SCREEN_WIDTH * 0.6,
    // height: SCREEN_HEIGHT * 0.5,
    // resizeMode: 'contain',
    // alignSelf: 'center',
    // top: SCREEN_HEIGHT * 0.2,
    // zIndex: 1,
  },
  together: {
    width: "100%",
    height: "80%",
  },
    message: {
    fontSize: 20,
    fontStyle: "italic",
    fontFamily: chosenFont,
    color: palette.darkBrown,
    lineHeight: 30,
    textAlign: 'center',
    paddingHorizontal: 30,
  },
  backToPortalButtonMain: {
    position: 'absolute',
    bottom: SCREEN_HEIGHT * 0.05,
    left: SCREEN_WIDTH * 0.5,
    transform: [{ translateX: -SCREEN_WIDTH * 0.2 }],
    backgroundColor: palette.lightBeige,
    paddingVertical: 16,
    //paddingHorizontal: 32,
    borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
    width: SCREEN_WIDTH * 0.4,
  },
  backToPortalButtonText: {
    fontSize: 18,
    fontFamily: chosenFont,
    color: palette.mediumBrown,
    fontWeight: '600',
  },
  backToPortalButton: {
    position: 'absolute',
    bottom: SCREEN_HEIGHT * 0.05,
    left: SCREEN_WIDTH * 0.1,
    backgroundColor: 'transparent',
    paddingVertical: 10,
    paddingHorizontal: 16,
    zIndex: 10,
  },
  backToPortalText: {
    fontSize: 16,
    fontFamily: chosenFont,
    color: palette.slate,
    textDecorationLine: 'underline',
  },
    sectionTitle: {
    fontSize: 28,
    fontFamily: chosenFont,
    color: palette.mediumBrown,
    fontWeight: '600',
    marginBottom: 24,
    textAlign: 'center',
  },
  bulletList: {
    marginBottom: 24,
    width: '100%',
    paddingHorizontal: 30,
  },
  bulletPoint: {
    fontSize: 18,
    fontFamily: chosenFont,
    color: palette.darkBrown,
    lineHeight: 32,
    marginBottom: 8,
  },
  prompt: {
    fontSize: 18,
    fontFamily: chosenFont,
    color: palette.darkBrown,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingHorizontal: 20,
    lineHeight: 26,
    marginBottom: 16,
  },
  textBox: {
    backgroundColor: palette.lightBeige,
    borderRadius: 16,
    padding: 16,
    fontSize: 17,
    fontFamily: chosenFont,
    color: palette.darkBrown,
    minHeight: 120,
    width: '90%',
    marginTop: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: palette.lightGray,
    textAlignVertical: 'top',
  },
  savebutton: {
    backgroundColor: palette.slate,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    width: '90%',
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  savebuttontext: {
    fontSize: 16,
    fontFamily: chosenFont,
    color: palette.cream,
    fontWeight: '600',
  },
  buttonRow: {
    flexDirection: 'row',
    width: '90%',
    gap: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButton: {
    backgroundColor: 'transparent',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: palette.slate,
    flex: 1,
  },
  cancelButtonText: {
    fontSize: 16,
    fontFamily: chosenFont,
    color: palette.slate,
    fontWeight: '600',
  },
  saveButtonEdit: {
    flex: 1,
  },
  editButton: {
    backgroundColor: palette.slate,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    width: '90%',
    marginTop: 8,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  editButtonText: {
    fontSize: 16,
    fontFamily: chosenFont,
    color: palette.cream,
    fontWeight: '600',
  },
  savedLabel: {
    fontSize: 16,
    fontFamily: chosenFont,
    color: palette.mediumBrown,
    fontWeight: '600',
    marginTop: 24,
    marginBottom: 8,
    textAlign: 'center',
  },
  savedTextBox: {
    backgroundColor: palette.lightBeige,
    borderRadius: 16,
    padding: 16,
    fontSize: 17,
    fontFamily: chosenFont,
    color: palette.darkBrown,
    minHeight: 120,
    width: '90%',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: palette.lightGray,
    textAlignVertical: 'top',
    opacity: 0.8,
  },
  scrollView: {
    flex: 1,
    width: '100%',
  },
  scrollContent: {
    paddingBottom: 120,
  },
  portalCallButton: {
  position: 'absolute',
  bottom: 110,
  left: SCREEN_WIDTH / 2 - 40,
  zIndex: 100,
},
portalCallButtonInner: {
  width: 80,
  height: 80,
  borderRadius: 40,
  backgroundColor: palette.slate,
  justifyContent: 'center',
  alignItems: 'center',
  shadowColor: palette.shadow,
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.3,
  shadowRadius: 8,
  elevation: 6,
},
});

export default portalStyles;