import { StyleSheet, Dimensions } from 'react-native';
import { palette } from './palette';
import theme from './theme';

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

// Global stylesheet for Tether app using extracted palette
const globalStyles = StyleSheet.create({
  // Containers
  container: {
    flex: 1,
    backgroundColor: palette.cream,
  },
  screen: {
    flex: 1,
    padding: 10,
  },

  content: {
    flex: 1,
    justifyContent: 'center',
  },
  scrollContent: {
    flex: 1,
  },
  centeredContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },

  // Login/Auth Styles
  loginContainer: {
    flex: 1,
    backgroundColor: palette.cream,
  },
  loginLogoContainer: {
    alignItems: 'center',
    marginBottom: 24,
  },
  loginLogo: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: palette.slate,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  logoutLogo:{
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: theme.button,
    padding: 16,
    borderRadius: 16,
    marginTop: 12,
  },
  titleLarge: {
    fontSize: 50,
    fontWeight: '700',
    textAlign: 'center',
    fontFamily: 'Avenir',
    color: palette.slate,
    marginBottom: 8,
  },
  titleSubtitleItalic: {
    fontSize: 16,
    fontStyle: 'italic',
    textAlign: 'center',
    fontFamily: 'Avenir',
    color: palette.lightBrown,
  },
  imagePlaceholder: {
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 24,
  },
  image:{
    width: windowWidth*0.8,
    height: 200
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Avenir',
    color: palette.mutedBrown,
    marginBottom: 8,
  },
  areaCodeContainer: {
    paddingRight: 8,
    borderRightWidth: 1,
    borderRightColor: palette.lightGray,
    marginRight: 8,
  },
  areaCodeText: {
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Avenir',
    color: palette.darkBrown,
  },
  loginInputPassword: {
    flex: 1,
    paddingVertical: 16,
    paddingLeft: 16,
    fontSize: 16,
    fontFamily: 'Avenir',
    color: palette.darkBrown,
  },
  signUpLinkContainer: {
    marginTop: 16,
    alignItems: 'center',
  },
  signUpLink: {
    fontSize: 16,
    fontFamily: 'Avenir',
    color: palette.mediumBrown,
    textDecorationLine: 'underline',
  },
  loginTitle: {
    fontSize: 32,
    fontWeight: '700',
    
    color: palette.mediumBrown,
    marginBottom: 4,
    textAlign: 'center',
  },
  loginSubtitle: {
    fontSize: 16,
    fontFamily: 'Avenir',
    color: palette.lightBrown,
    textAlign: 'center',
    opacity: 0.8,
  },
  loginInputContainer: {
    marginLeft: 16,
    marginRight: 16,
    marginBottom: 16,
  },
  loginInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: palette.cream,
    width: windowWidth * 0.9,
    borderRadius: 30,
    paddingHorizontal: 16,
    paddingVertical: 0,
    borderWidth: 1,
    borderColor: palette.lightGray,
  },
  loginInputIcon: {
    marginRight: 12,
  },
  loginInput: {
    flex: 1,
    paddingVertical: 16,
    fontSize: 16,
    fontFamily: 'Avenir',
    color: palette.darkBrown,
  },
  loginButton: {
    backgroundColor: palette.slate,
    padding: 18,
    borderRadius: 30,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    width: windowWidth*0.3,
    marginBottom: 12,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
    marginTop: 16,
  },
  loginButtonDisabled: {
    opacity: 0.6,
  },
  loginButtonText: {
    color: palette.cream,
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'Avenir',
  },

  loginFooterText: {
    textAlign: 'center',
    marginTop: 32,
    fontSize: 13,
    color: palette.mutedBrown,
    opacity: 0.6,
    lineHeight: 20,
  },

  // Typography
  logo: {
    fontSize: 80,
    textAlign: 'center',
    marginBottom: 24,
  },
  title: {
    fontSize: 48,
    fontWeight: '700',
    textAlign: 'center',
    color: palette.mediumBrown,
    marginBottom: 16,
  },
  heading: {
    fontSize: 28,
    fontWeight: '600',
    color: palette.slate,
    marginBottom: 20,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center"
  },
  backButton: {
    position: 'absolute',
    justifyContent: "center",
    left: 8,
    zIndex: 1,
  },
  headingtext: {
    fontSize: 30,
    fontWeight: '700',
    color: palette.slate,
    fontFamily: 'Avenir',
  },
  subheading: {
    fontSize: 22,
    fontWeight: '600',
    fontFamily: 'Avenir',
    color: palette.slate,
    marginBottom: 16,
  },
  subtitle: {
    fontSize: 18,
    fontFamily: 'Avenir',
    textAlign: 'center',
    color: palette.lightBrown,
    lineHeight: 26,
  },
  empty: {
    fontFamily: 'Avenir',
    marginBottom: 20,
    marginLeft: 20,
  },
  search: {
    flexDirection: "row",
    justifyContent: "flex-start",
    padding: 3,
    borderRadius: 30,
    height: 35,
    backgroundColor: theme.bg,
    marginLeft: 10,
    marginRight: 10,
    marginBottom: 10,
  },
  searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
  },
  searchInput: {
      flex: 1,
  },
  body: {
    fontSize: 17,
    fontFamily: 'Avenir',
    color: palette.darkBrown,
    lineHeight: 24,
  },
  bodySecondary: {
    fontSize: 17,
    fontFamily: 'Avenir',
    color: palette.lightBrown,
    lineHeight: 22,
  },
  caption: {
    fontSize: 13,
    fontFamily: 'Avenir',
    color: palette.mutedBrown,
  },
  label: {
    fontSize: 15,
    fontWeight: '600',
    fontFamily: 'Avenir',
    color: palette.mediumBrown,
    marginBottom: 8,
  },
  text: {
    fontSize: 16,
    fontWeight: '400',
    fontFamily: 'Avenir',
    color: palette.mediumBrown,
  },

  // Buttons
  button: {
    backgroundColor: palette.slate,
    padding: 24,
    borderRadius: 20,
    alignItems: 'center',
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  buttonSecondary: {
    backgroundColor: palette.teal,
    padding: 24,
    borderRadius: 20,
    alignItems: 'center',
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  buttonOutline: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: palette.slate,
    padding: 24,
    borderRadius: 20,
    alignItems: 'center',
  },
  buttonSmall: {
    padding: 8,
    paddingHorizontal: 16,
  },
  buttonText: {
    color: palette.cream,
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Avenir',
  },
  buttonTextOutline: {
    color: palette.slate,
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Avenir',
  },
  buttonTextSmall: {
    fontSize: 15,
    fontFamily: 'Avenir',
  },

  backText: {
    fontSize: 17,
    fontFamily: 'Avenir',
    color: palette.slate,
  },
  footer: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: palette.cream,
    borderTopWidth: 1,
    paddingBottom: 20,
    borderTopColor: palette.divider,
  },
  navButton: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-around',
    color: palette.lightBrown,
    alignItems: 'center',
    margin: 10,
  },

  // Cards
  card: {
    backgroundColor: palette.lightBeige,
    padding: 16,
    borderRadius: 16,
    marginBottom: 8,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  cardElevated: {
    backgroundColor: palette.lightBeige,
    padding: 24,
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  dropdown:{
    flexDirection: "row",
    marginLeft: 5,
    marginTop: 10,
  },
  contactCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: palette.cream,
    padding: 5,
    borderRadius: 16,
    marginBottom: 10,
    marginLeft: 20,
    marginRight: 20,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: palette.cream,
    borderColor: palette.cream,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  avatarText: {
    color: palette.cream,
    fontSize: 18,
    fontWeight: '600',
  },
  contactName: {
    fontSize: 17,
    fontFamily: 'Avenir',
    color: palette.darkBrown,
    fontWeight: '500',
  },

  // Input Fields
  input: {
    backgroundColor: palette.lightBeige,
    borderRadius: 16,
    padding: 16,
    fontSize: 17,
    fontFamily: 'Avenir',
    color: palette.darkBrown,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: palette.lightGray,
  },
  inputMultiline: {
    backgroundColor: palette.lightBeige,
    borderRadius: 16,
    padding: 16,
    fontSize: 17,
    fontFamily: 'Avenir',
    color: palette.darkBrown,
    minHeight: 100,
    textAlignVertical: 'top',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: palette.lightGray,
  },

  // Tabs
  tabs: {
    flexDirection: 'row',
    marginBottom: 24,
    backgroundColor: palette.lightBeige,
    borderRadius: 16,
    padding: 4,
  },
  tab: {
    flex: 1,
    padding: 8,
    alignItems: 'center',
    borderRadius: 12,
  },
  tabActive: {
    backgroundColor: palette.beige,
  },
  tabText: {
    fontSize: 15,
    fontFamily: 'Avenir',
    color: palette.mutedBrown,
  },
  tabTextActive: {
    fontSize: 15,
    fontFamily: 'Avenir',
    color: palette.slate,
    fontWeight: '600',
  },

  // Message Box
  messageBox: {
    backgroundColor: palette.lightBeige,
    padding: 24,
    borderRadius: 16,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  message: {
    fontSize: 17,
    fontFamily: 'Avenir',
    color: palette.darkBrown,
    lineHeight: 24,
  },

  // Phase Cards
  phaseCard: {
    backgroundColor: palette.lightBeige,
    padding: 32,
    borderRadius: 16,
    alignItems: 'center',
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  phaseTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: palette.mediumBrown,
    marginBottom: 16,
    textAlign: 'center',
  },
  phaseText: {
    fontSize: 17,
    fontFamily: 'Avenir',
    color: palette.lightBrown,
    textAlign: 'center',
    lineHeight: 24,
  },

  // Lists
  list: {
    flex: 1,
  },
  listItem: {
    backgroundColor: palette.lightBeige,
    padding: 16,
    borderRadius: 12,
    marginBottom: 4,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  listItemText: {
    fontSize: 17,
    fontFamily: 'Avenir',
    color: palette.darkBrown,
  },

  // Dividers
  divider: {
    height: 1,
    backgroundColor: palette.divider,
    marginVertical: 5,
  },
  dividerThick: {
    height: 2,
    backgroundColor: palette.divider,
    marginVertical: 24,
  },
  popup:{
    width: windowWidth * 0.6,
    height: windowHeight * 0.3,
    
    alignItems: "center",
  },

  // Spacing Utilities
  marginBottomSm: {
    marginBottom: 8,
  },
  marginBottomMd: {
    marginBottom: 16,
  },
  marginBottomLg: {
    marginBottom: 24,
  },
  marginTopSm: {
    marginTop: 8,
  },
  marginTopMd: {
    marginTop: 16,
  },
  marginTopLg: {
    marginTop: 24,
  },
  paddingMd: {
    padding: 16,
  },
  paddingLg: {
    padding: 24,
  },

  // Alignment Utilities
  centerAlign: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowAlign: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  spaceBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },

  // Status/Alert Cards
  successCard: {
    backgroundColor: palette.sage + '20',
    padding: 16,
    borderRadius: 16,
    borderLeftWidth: 4,
    borderLeftColor: palette.sage,
    marginBottom: 16,
  },
  warningCard: {
    backgroundColor: palette.coral + '20',
    padding: 16,
    borderRadius: 16,
    borderLeftWidth: 4,
    borderLeftColor: palette.coral,
    marginBottom: 16,
  },
  errorCard: {
    backgroundColor: palette.coral + '30',
    padding: 16,
    borderRadius: 16,
    borderLeftWidth: 4,
    borderLeftColor: palette.coral,
    marginBottom: 16,
  },
  accentCard: {
    backgroundColor: palette.teal + '20',
    padding: 16,
    borderRadius: 16,
    borderLeftWidth: 4,
    borderLeftColor: palette.teal,
    marginBottom: 16,
  },
  profileHeader: {
    padding: 20,
    backgroundColor: palette.lightBeige,
    borderRadius: 20,
    marginBottom: 16,
  },
  profileAvatarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
    marginBottom: 16,
  },
  profileAvatar: {
    width: 85,
    height: 85,
    borderRadius: 42.5,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    elevation: 4,
  },
  profileAvatarImage: {
    width: 70,
    height: 70,
    resizeMode: 'contain',
  },
  profileInfo: {
    flex: 1,
  },
  profileNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  profileUsername: {
    fontSize: 26,
    fontWeight: '700',
    fontFamily: 'Avenir',
    color: palette.darkBrown,
    flex: 1,
  },
  editButton: {
    backgroundColor: palette.slate,
    padding: 10,
    borderRadius: 20,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  profileBio: {
    fontSize: 15,
    fontFamily: 'Avenir',
    fontStyle: "italic",
    color: palette.lightBrown,
    lineHeight: 20,
    marginBottom: 4,
  },
  profilePhone: {
    fontSize: 13,
    fontFamily: 'Avenir',
    color: palette.mutedBrown,
    opacity: 0.7,
  },
  logoutButton: {
    backgroundColor: palette.coral,
    padding: 18,
    borderRadius: 20,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  
  // Modal styles
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: palette.cream,
    borderRadius: 20,
    padding: 24,
    width: '85%',
    maxHeight: '75%',
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: palette.darkBrown,
  },
  modalLabel: {
    fontSize: 15,
    fontWeight: '600',
    fontFamily: 'Avenir',
    color: palette.mediumBrown,
    marginBottom: 8,
  },
  modalInput: {
    backgroundColor: palette.lightBeige,
    padding: 16,
    borderRadius: 16,
    fontSize: 16,
    fontFamily: 'Avenir',
    color: palette.darkBrown,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: palette.lightGray,
  },
  modalInputMultiline: {
    minHeight: 100,
    textAlignVertical: 'top',
  },
  colorPicker: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 24,
  },
  colorOption: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  colorOptionSelected: {
    borderWidth: 3,
    borderColor: palette.cream,
  },
  saveButton: {
    backgroundColor: palette.slate,
    padding: 18,
    borderRadius: 16,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  saveButtonText: {
    color: palette.cream,
    fontSize: 17,
    fontWeight: '700',
    fontFamily: 'Avenir',
  },
  userGraphicItem: {
    alignItems: 'center',
  },
  userImg:{
    flexDirection: "row", 
    marginBottom: 0,
    justifyContent: "center"
  },
  userGraphic:{
    flexDirection: "row", 
    gap: 60, 
    marginBottom: 10,
    justifyContent: "center"
  },
  userGraphicLabel: {
    fontSize: 18,
    fontFamily: 'Avenir',
    color: palette.mutedBrown,
    marginTop: 2,
  },
  chatContainer: {
    flex: 1,
    marginBottom: 10,
  },
  messageBubble: {
    padding: 16,
    borderRadius: 16,
    marginBottom: 12,
    maxWidth: '85%',
  },
  aiMessage: {
    backgroundColor: palette.lightBeige,
    alignSelf: 'flex-start',
  },
  userMessage: {
    backgroundColor: palette.lightGray,
    alignSelf: 'flex-end',
  },
  aiLabel: {
    fontSize: 12,
    fontFamily: 'Avenir',
    color: palette.slate,
    marginBottom: 8,
  },
  messageText: {
    fontSize: 15,
    fontFamily: 'Avenir',
    color: palette.shadow,
    lineHeight: 22,
  },
  inputArea: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  chatInput: {
    flex: 1,
    backgroundColor: palette.cream,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 15,
    fontFamily: 'Avenir',
    fontStyle: "italic",
    color: palette.darkBrown,
    borderWidth: 1,
    borderColor: palette.lightGray,
    maxHeight: 100,
  },
  sendButton: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  successModal: {
    backgroundColor: palette.cream,
    borderRadius: 20,
    padding: 40,
    alignItems: 'center',
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  modalCloseButton: {
    position: 'absolute',
    top: 16,
    right: 16,
  },
  successText: {
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 5,
    color: palette.darkBrown,
    fontFamily: 'Avenir',
  },

});

export default globalStyles;